### PR TITLE
Add basic support for docker

### PR DESCRIPTION
**Pull request by mfarr**
Adds basic support for running evl-simulator interactively in a Docker container. This will make it easier to use on systems without Erlang/Elixir installed.

### CODE REVIEW

**Comment by mfarr** [comment]
@zaid I'm using the OTP 24 compatible version of Elixir, not sure if that's the ideal choice. I'll leave that to you as our resident Elixir expert.

**Comment by zaid** [comment]
> @zaid I'm using the OTP 24 compatible version of Elixir, not sure if that's the ideal choice. I'll leave that to you as our resident Elixir expert.

@mfarr I'm using the latest version locally (Elixir 1.15.x and OTP 26), is it possible to bump the version to that?

**Comment by mfarr** [comment]
@zaid Yep, no problem. Its now using 1.15.x rather than latest, but we can update it once 1.16 is released and we've made sure its compatible.

**Review by zaid — APPROVED** [review]
Looks great! thanks for doing this 😄

**Pull request merged**
